{% set name = "tokenize-output" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b31e75f52ae21099f8e10b6e2dc2cfdedae5a544fdbc3df963273b06bc8cd80d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh
    - demjson

test:
  imports:
    - tokenize_output

about:
  home: https://github.com/tokenizer/tokenize-output
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Get identifiers, names, paths, URLs and words from the command output.
  doc_url: https://github.com/tokenizer/tokenize-output/blob/master/README.md
  dev_url: https://github.com/tokenizer/tokenize-output

extra:
  recipe-maintainers:
    - scopatz
